# Generated by Django 6.0 on 2025-12-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('purchase_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('stock', models.IntegerField(default=0)),
                ('gst_percent', models.FloatField(default=0)),
            ],
        ),
    ]
