# Generated by Django 6.0 on 2025-12-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='purchase_price',
            new_name='due_amount',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='selling_price',
            new_name='paid_amount',
        ),
        migrations.AddField(
            model_name='sale',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(default='PAID', max_length=10),
            preserve_default=False,
        ),
    ]
